### ISSUE TITLE
pls support 1.8!!

### ISSUE THREAD

**Issue by MylesIsCool** [Matsv/ViaBackwards#1]
plz add 1.8 thx

**Comment by Matsv** [comment]
No, 1.8 should die. Blame ViaVersion for trying to rescue 1.8!!!!!!!!! 

(For people with too much time, and wanting to create it. Feel free to do it and send a PR)

**Comment by TiTo-418** [comment]
@Matsv Why not just use protoclsupport?

**Comment by Matsv** [comment]
@Tito-418 this is mainly a project for my own server. I don't want all protocol version to be supported, only 1.9-1.10. The changes between 1.9 and 1.10 are not that big. So that's why I'm making it myself.

**Comment by TiTo-418** [comment]
Well, you can choose what version you want to allow with this plugin https://www.spigotmc.org/resources/blockversion-for-protocolsupport.21202/

**Comment by Matsv** [comment]
@Tito-418 true, but I prefer creating it myself :). Oh and protocolsupport for 1.10 is not released yet.

**Comment by TiTo-418** [comment]
Dev build are for spigot 1.10.2, anyways, good luck :smile:

**Comment by Matsv** [comment]
@TiTo-418 Thanks :wink:

**Comment by Techcraft7** [comment]
what about the 1.8 pvp community?

**Comment by krusic22** [comment]
ViaRewind exists.
