### ISSUE TITLE
EntityRewriter throws NPE 

### ISSUE THREAD

**Issue by DuckCraftPvP** [Matsv/ViaBackwards#11]
### What is the output url of /viaversion dump?
> 

### How/when does this error happen? login?:
> 
randomly kicks you from game.
### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> 
https://hastebin.com/qeyujijiru.md

**Comment by Matsv** [comment]
Thanks for letting me know, will fix it tomorrow.

**Comment by Matsv** [comment]
Could you try if this occurs with only ViaVersion/ViaBackwards enabled? I can handle the error, but that won't stop the issue that (one of your plugins) is sending wrong entity ids that don't exist, or that I didn't handle an entity, which is also a possibility ofcourse. 

Thanks (:

**Comment by DuckCraftPvP** [comment]
i removed viabackwards and it works fine and does not kick people.

**Comment by Matsv** [comment]
Ofcourse, the exception is not good, that'll be fixed the next push, but that doesn't take the possibility away that one of your plugins might be sending wrong data.

**Comment by DuckCraftPvP** [comment]
ok, Thank you and il look more into it.

**Comment by Matsv** [comment]
Crash should be fixed in the latest devbuild (https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/). I'd love to hear from you if it occurs with only ViaVersion & ViaBackwards installed (:
