### ISSUE TITLE
ViaBackwards

### ISSUE THREAD

**Issue by Callatic** [Matsv/ViaBackwards#12]
### What is the output url of /viaversion dump?
> https://gist.github.com/63dd0a84b2a971d9e220fa0119bffcbd

### How/when does this error happen? login?:
> I have ViaVersion, ViaBackwards and ProtocolLib installed and I run Spigot 1.12 but when I try join with 1.8 or any other version it doesnt work and says outdated

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No error message

**Comment by Matsv** [comment]
Works as intended.

As mentioned on the resourcepage & FAQ:

> Please support 1.8 and lower? 
No, use ProtocolSupport if you want Backwards compatibility for 1.8 and lower.

![versions](https://proxy.spigotmc.org/57217bb943425bdc114cc182bcba3b1f9539ecfa?url=http%3A%2F%2Fi.imgur.com%2FgXCifhK.png)
