### ISSUE TITLE
Error when changing servers

### ISSUE THREAD

**Issue by steven5297norton** [Matsv/ViaBackwards#13]
### What is the output url of /viaversion dump?
> https://gist.github.com/anonymous/0929c2ffbbb519770c4629cdfa451900 -bungee
> https://gist.github.com/anonymous/504fad31c4e5b0333d741dd33bc824dd -bedwars

### How/when does this error happen? login?:
> When do /server bedwars
or use bungeeportals

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> error only in bungee
>https://pastebin.com/B4vy1GaG
>Kick message http://prntscr.com/fn08sv

**Comment by Matsv** [comment]
Sorry for the late response.
Does this happen If you use the same client version as spigot version?

**Comment by steven5297norton** [comment]
Yes it does.

**Comment by Matsv** [comment]
In that case it isn't caused by ViaBackwards nor ViaVersion. We only handle non-server versions. Try to debug it by removing plugins until it no longer happens. (:
