### ISSUE TITLE
Players are kicked as they change from world...

### ISSUE THREAD

**Issue by ItsMennyo** [Matsv/ViaBackwards#14]
### What is the output url of /viaversion dump?
> Expired...

### How/when does this error happen? login?:
> I have 2 maps in my server. I have a spawn and I have a survival map. If you join the server you will be in the spawn and if players want to go to the survival map they will be kicked every time. But, this happens only when they play in 1.11 (I have not tried 1.10 and 1.9 yet). If you joining with 1.12 then there is no problem.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> There are no errors in the console so I've taken pictures of what this has to do with: http://imgur.com/a/WwRwG

Hopefully you will find a solution quickly because players find it very annoying!

Thanks!

**Comment by Matsv** [comment]
Please enable debug in server.properties and give the full exception (:

**Comment by ItsMennyo** [comment]
Update spigot to the latest version did the trick?
Even if I turned on the debug in server.properties nothing happened and this also applies to spigot.yml

I'll let the debug on if it happens again (If then the debug works again lmao)

**Comment by ItsMennyo** [comment]
@Matsv Got it: https://pastebin.com/HywZpVtc

(I did not get it for a while so I thought Spigot updating had utility but no)

**Comment by ItsMennyo** [comment]
Another one: https://pastebin.com/B0UpN0cw

**Comment by Matsv** [comment]
First one is fixed in the latest devbuild, second one is not ViaBackwards related.

**Comment by ItsMennyo** [comment]
@Matsv Updated ViaBackwards ans ViaVersion to te last dev builds and it still hapends: https://pastebin.com/c57jASry

**Comment by Matsv** [comment]
Please try this build http://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/

**Comment by ItsMennyo** [comment]
Now it works. Sometimes it takes a lot of time before you get it again so if I get back to it I will notify you

Thanks in advance!

**Comment by ItsMennyo** [comment]
@Matsv Now I only get this: https://pastebin.com/rxwbavKZ

**Comment by Matsv** [comment]
One of your plugins is sending metadata for a not (yet) initialized entity or a non existing type. Please try to debug it by removing some plugins to see which one is doing it. I'll add an option to hide that warning soon.

TODO: possibility to hide msg

**Comment by ItsMennyo** [comment]
Okay, but if I have to remove 1 for 1 the plugins, I can only test it every hour. If I restart the server, I do not have that problem. Sometimes I have to wait for an hour that it's out of the cache or so...

**Comment by ItsMennyo** [comment]
But what strikes me is that 2286 (and also all other IDs) does not even exist. Also not in a minecraft 1.12 id list...

![knipskjhkhjkhjkel](https://user-images.githubusercontent.com/25391253/27699916-37d3b0f2-5cfc-11e7-9838-081840b8d828.PNG)

**Comment by Matsv** [comment]
Thats the entity id in the exception, not block id. (:

**Comment by ItsMennyo** [comment]
Oh, I already thought xD

**Comment by ItsMennyo** [comment]
Maybe because I'm going to another world where those entitys exist?

**Comment by Matsv** [comment]
Well normally it'll spawn / despawn the entities on world switch, but it could be the problem if one of your plugins is sending wrong data.
