### ISSUE TITLE
only 1.9/1.10??

### ISSUE THREAD

**Issue by BARANLANKA** [Matsv/ViaBackwards#2]
i was wondering if you could make support for 1.8. by this i mean that a 1.9 server will support 1.8
pls answer as fast as possible

**Comment by Matsv** [comment]
I'm sorry, adding support for 1.8 will take too much time ( think about 40 hours constant work ) to get it working good. I don't have the time to do that. I recommend you to use [ProtocolSupport](https://www.spigotmc.org/resources/protocolsupport.7201/) instead, that plugin supports 1.9 - 1.4.7 IIRC.

**Comment by BestMark** [comment]
ProtocolSupport has one considerable bug with chunk loading only at 1.8.x versions.
When players has joined, chunks around are invincible, and blocks are transparent.

**Comment by Matsv** [comment]
@BestMark Report it as issue? https://github.com/ProtocolSupport/ProtocolSupport/issues 
Developers can't know bugs if nobody reports them ;)

**Comment by BestMark** [comment]
@Matsv https://github.com/ProtocolSupport/ProtocolSupport/issues/145
