### ISSUE TITLE
Console Error - Unknown Reason

### ISSUE THREAD

**Issue by YugieDev** [Matsv/ViaBackwards#20]
### What is the output url of /viaversion dump?
https://gist.github.com/d35c8f171b66e7ae9e01a236f1272e91

### How/when does this error happen? login?:
It's be happening randomly throughout the console

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
https://hastebin.com/huqafomeju.scala

**Comment by Matsv** [comment]
One of your plugins is sending metadata before spawning the entity. I'd recommend debugging it by removing plugins one by one until it no longer happens to find your issue. However, you can also ignore this warning by changing suppress-metadata-errors to true in the ViaVersion config.
