### ISSUE TITLE
1.12.1 Server cant connect with 1.11.2

### ISSUE THREAD

**Issue by steven4547466** [Matsv/ViaBackwards#22]
### What is the output url of /viaversion dump?
> All I have is a config file on the ViaVersion folder, also ViaBackwards does not give me any config at all

### How/when does this error happen? login?:
> I'm trying to connect with 1.11.2 on a 1.12.1 server, it doesnt seem to work, I have both ViaVersion and ViaBackwards.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No errors

**Comment by Matsv** [comment]
Please follow the issue template. I need the ViaVersion dump output to help you. Also what is the disconnect messagd on 1.11.2?

**Comment by steven4547466** [comment]
I cant find the VIaVersion dump, its not in any folders in ViaVersion... the Kick message is simply "Outdated client! Please use 1.12.1!"

**Comment by Matsv** [comment]
It's a command you need to execute, it'll output a link

**Comment by steven4547466** [comment]
Sorry, I'm dumb, here it is https://gist.github.com/900c5f7c90521b54cbbefe4e2436e8e6

**Comment by Matsv** [comment]
Don't forget to read your startup log, ViaVersion has to be updated to the latest version. ;)

**Comment by steven4547466** [comment]
Alright, thanks

**Comment by steven4547466** [comment]
I feel dumb now ;-;

**Comment by Matsv** [comment]
Don't worry about it, happy to hear it works now. ;)
