### ISSUE TITLE
Kicking me and other people saying Proxy connection lost

### ISSUE THREAD

**Issue by Haspra** [Matsv/ViaBackwards#23]
### What is the output url of /viaversion dump?
>  im using viaversion 1.2.0 and viabackwards 2.2.0

### How/when does this error happen? login?:
>  when somebody login and try to go out of spawn point

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
>  >[2K [19:20:37 INFO]: Haspra[/46.150.192.185:50531] logged in with entity id 3597 at ([Hub]0.8692732196739223, 30.0, 0.4902471505261161) 
>[2K [19:20:38 INFO]: [AuthMe] Haspra logged in! 
>[2K [19:20:39 INFO]: Haspra lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

**Comment by Matsv** [comment]
Could you change 'debug' to 'true' in the file 'server.properties' and paste the full exception? (:

**Comment by Matsv** [comment]
And please give me your ViaVersion dump

**Comment by bigdaddyroughnuts** [comment]
I'm having the same issue. I'm enabling debug and will report back.

**Comment by Matsv** [comment]
Thanks (:

**Comment by Matsv** [comment]
Closing because you never reported back. Ask for a reopen if you can provide more information! (:
