### ISSUE TITLE
slab is being placed in bottom part when facing to highest part of block

### ISSUE THREAD

**Issue by smessie** [Matsv/ViaBackwards#25]
### What is the output url of /viaversion dump?
> https://gist.github.com/anonymous/e7c3d792952d920c965be951d1d2675a

### How/when does this error happen? login?:
> When a player on 1.10.2 with 1.12.1 server places a slab or stair it places it with default rotation so even when the player faces to the highest part of a block, it places the slab on the bottom part anyways.
Same rotation issue with stairs.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> nope

**Comment by gabe23** [comment]
This planning on been fixed?

**Comment by Matsv** [comment]
I’m sadly very limited on time. I’m not sure when it’ll be fixed.
