### ISSUE TITLE
Viabackwards wont even install on version 1.12

### ISSUE THREAD

**Issue by AdvancedGP** [Matsv/ViaBackwards#27]
### What is the output url of /viaversion dump?
> Do not know

### How/when does this error happen? login?:
> when i try to install

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> this is what happens when u use plugman to load it: https://pastebin.com/cbqadUYX

**Comment by Matsv** [comment]
This issue is not related to ViaBackwards. Restart your server instead of loading ViaVersion/ViaBackwards with plugman
