### ISSUE TITLE
BungeeCord

### ISSUE THREAD

**Issue by XakepSDK** [Matsv/ViaBackwards#28]
### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://pastebin.com/xeLv99te

Please, handle empty arrays correctly. I hope, you fix this.

**Comment by Matsv** [comment]
Hey,

This is down to one of your other plugins that modifies chunks.
Chunk sections aren't supposed to have an empty block array.
It checks here if the section is empty (when the chunk is sent correctly): https://github.com/Matsv/ViaBackwards/blob/master/core/src/main/java/nl/matsv/viabackwards/api/rewriters/BlockItemRewriter.java#L149

I´d recommend debugging your plugins to find out which plugin is causing this issue.

Let me know if you have any further questions.

Regards,
Mats
