### ISSUE TITLE
Bungee console spam "Metadata for entity id not sent"

### ISSUE THREAD

**Issue by ArtNRG** [Matsv/ViaBackwards#29]
### What is the output url of /viaversion dump?
> https://gist.github.com/f83fd0e2bafa2dacf474779447b8a3d3

### How/when does this error happen? login?:
>  Bungee console is spammed with the warning messages "Metadata for entity id: ... not sent". Seems like it's happen always.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://pastebin.com/GMjjhSpi

**Comment by Matsv** [comment]
One of your spigot plugins is sending wrong metadata.

I'd recommend debugging your plugins to find out which one is doing it.
If you don't care about it, you can just change 'suppress-metadata-errors' to 'true' in the ViaVersion config.
