### ISSUE TITLE
1.9 clients get disconnect when go to the nether

### ISSUE THREAD

**Issue by MClausz** [Matsv/ViaBackwards#3]
### What is the output url of /viaversion dump?
http://hastebin.com/iwutawiqig.json

### How/when does this error happen? login?:
teleport to the nether, unable to connect back after get kicked, until they switch to 1.10

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
http://i.imgur.com/URFCtaq.png
No console error.

**Comment by Matsv** [comment]
I can't reproduce this with only ProtocolLib, ViaVersion and ViaBackwards. Could you try to debug it? Remove some plugins for testing until you find the one that is conflicting?

**Comment by MClausz** [comment]
Lib's Disguises 9.0.9 (lastest version) was the cause, I can go to the nether after uninstalling it.
Well but I need it, tho.

**Comment by Matsv** [comment]
I'll take a look at it when I have the time. :)

**Comment by MClausz** [comment]
Tested with Lib's Disguise, Multiverse Core, Viaversion, ViaBackwards, Protocollib
All are latest version

**Comment by Matsv** [comment]
I'm unable to reproduce it with those plugins.

I tried:
- Going to the nether through a portal
- Creating a nether world with Multiverse-core and mvtp to it

**ViaDump:** http://hastebin.com/wubihalapi.json

It looks like that you are using a devbuild of ProtocolLib and Multiverse-Core. Please try to use the latest official version of it.

**Comment by MClausz** [comment]
I just changed to Protocollib 4.0.2 and it works fine, thanks.

**Comment by Matsv** [comment]
Great to hear that

**Comment by MClausz** [comment]
Wait a minute... Lib's Disguises didn't start with Protocollib 4.0.2... lol
`[03:44:29] [Server thread/INFO]: [LibsDisguises] Enabling LibsDisguises v9.0.9
[03:44:29] [Server thread/WARN]: [LibsDisguises] Lib's Disguises failed to startup, outdated ProtocolLib!
[03:44:29] [Server thread/WARN]: [LibsDisguises] You need to update ProtocolLib, please try this build http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/artifact/modules/ProtocolLib/target/ProtocolLib.jar`

**Comment by Matsv** [comment]
Could you try using the latest devbuild of LibsDisguises?

**Comment by MClausz** [comment]
Tried devbuild of Lib's Disguise, still occur

**Comment by Matsv** [comment]
Being incompatible with the latest ProtocolLib is something LibsDiguises should fix, I can't support you for that. You could try to use the build of ProtocolLib that LibsDiguises mentioned with the incompatible message.

**Comment by MClausz** [comment]
The latest devbuild of ProtocolLib (4.1.0) is a newer version of the latest one on spigot (4.0.2)

**Comment by RoboMWM** [comment]
So I switched to ViaBackwards and ViaVersion after discovering 1.9 players were getting disconnected when receiving a command to play a custom sound. Well, now I have this issue as well :( and it isn't just on change... I can't login again after this happens.

Using Protocollib 4.1.0 and libsdisguises 9.0.9 (both "snapshot" versions).

**Comment by Matsv** [comment]
@RoboMWM Could you please open a new issue for this one? It'd be useful if you could provide some kind of resourcepack and a method to reproduce it. Thanks.

**Comment by RoboMWM** [comment]
The kick message as well as the plugins at play are the exact same as here.

**Comment by Matsv** [comment]
@RoboMWM How to reproduce it, how do you send your resourcepack and what playsound command do you use?

**Comment by RoboMWM** [comment]
Oh, you meant that issue, that was an issue with ProtocolSupport that drove me to use this plugin, sorry for not making that clear :P

**Comment by Matsv** [comment]
@RoboMWM Oh, I also read it wrong, sorry about that. Could you try if it also works again for you without LibsDiguises?

**Comment by Matsv** [comment]
Alright, I found a way to reproduce it. I don't have the time today to take a good look at it. Will do it tomorrow.

**Comment by Matsv** [comment]
@RoboMWM  @MClausz 
Should be fixed with the latest DevBuild (https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/).
This is a temporary fix, LibsDisguises is sending too big chunks. I currently don't have the time to really look into it, hence this small patch.
