### ISSUE TITLE
1.12.2 support

### ISSUE THREAD

**Issue by DynamicThijs** [Matsv/ViaBackwards#30]
### What is the output url of /viaversion dump?
https://gist.github.com/anonymous/e922f33140432bcca0b91a66e3d60388

### How/when does this error happen? login?:
At login

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
1.12.2 is not supported, I can only join using 1.12.2, but not lower anymore.

**Comment by midnjerry** [comment]
It looks like Matsv has to add: Protocol protocol1_12_1to1_12_2, but I don't know how difficult that would be.  I am also seeing the same thing on my server.

**Comment by TheZenKitteh** [comment]
I'm not seeing any errors but clients lower than 1.12.2 can't connect anymore.

**Comment by MylesIsCool** [comment]
Implemented :) 

See https://ci.viaversion.com/job/ViaBackwards/ for download
