### ISSUE TITLE
2 Issues

### ISSUE THREAD

**Issue by TuaCarnifex** [Matsv/ViaBackwards#32]
### What is the output url of /viaversion dump?
>  Nothing, I see on commands help for viaversion. My server is updated to 1.12.1 and I am using version 2.2.0. When I try logging in on an outdated client I see it says "Bungeecord 1.8x-1.12x" which is exactly what I want. So I know it's installed right but still recieve no files, etc.

### How/when does this error happen? login?:
> Aside from the no files part.. Whenever I try actually loading into the server on something not 1.12.1 that fits the viabackwards standards it shows I am logging in then just disconnects me every time. I don't know why this happens.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No I restart and reload console. The only thing I see about console is checking server version but am not 100% sure that applies to this. Even if it does all versions are 1.12.1 I have triple checked that.

**Comment by MylesIsCool** [comment]
Type the command "/viaversion dump" then provide the url from it.

"So I know it's installed right but still recieve no files, etc.", what does this mean?

Also provide the version of your BungeeCord, (build number from the startup log)

**Comment by Matsv** [comment]
We need more information in order to help you.
Please ask for a reopen if you can provide it! (:
