### ISSUE TITLE
could not find type id -1 isObject=false console spam

### ISSUE THREAD

**Issue by aaa8881** [Matsv/ViaBackwards#33]
### What is the output url of /viaversion dump?
> https://gist.github.com/anonymous/cec73700502604106fe8eeac6b72572a

### How/when does this error happen? login?:
> when using holograms via skript addon skrayfall which uses holographic displays, i get this warn in console. here is a script (Skript script ) you can use to reproduce this
```
command /holotest:
	trigger:
		create holo object "testtesttest" with id "test" at player's location	
		edit holo object "test" line 1 to "changedtest"	
```

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> The only problem is large spam of this one message, no functionality error or anything
```
[ViaVersion] Could not find type id -1 isObject=false
```

**Comment by Matsv** [comment]
That plugin is sending wrong data to the client. I’d recommend contacting the developer to get it fixed inside the plugin. You can hide the warning in the ViaVersion config by changing ‘suppress-metadata-errors’ to ‘true’
