### ISSUE TITLE
1.12 blocks not working on 1.12

### ISSUE THREAD

**Issue by beautifulpoison** [Matsv/ViaBackwards#35]
### What is the output url of /viaversion dump?
>  I apparently cannot do this command...

### How/when does this error happen? login?:
> On my 1.12 server we cannot place 1.12 blocks it says that they are other versions blocks. This was working not to long ago then all the sudden it stopped working. I am in 1.12 and my server is on 1.12 we are using ViaBackwards and ViaVersion. 

In the photo it shows that it is a 1.12 item but its displayed as clay instead of concret. 
![screen shot 2017-11-30 at 8 49 09 am](https://user-images.githubusercontent.com/29660713/33436705-67411c12-d5ab-11e7-8106-93be155cbf23.png)

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No Errors.

**Comment by MylesIsCool** [comment]
Provide more details about your platform / setup, do you use BungeeCord?

You should be able to run "/viaversion dump" from the console.

**Comment by beautifulpoison** [comment]
I do use bungee and we have to have the plugin on both servers for it to work, you've been speaking with my dev Jean about an issue. 

/viaversion dump will not run in game or on the console.

**Comment by beautifulpoison** [comment]
We tried removing it from Bungee and from the server and one would not work without the other

**Comment by MylesIsCool** [comment]
Don't run ViaVersion on both, as said on the spigot page it's for one or the other.

That will be your issue. Ensure your BungeeCord is updated otherwise.

**Comment by TeamGameRevolution** [comment]
Hi, I'm that dev ^^ You replied to me yesterday.

Bungee dump: https://gist.github.com/anonymous/2dfc1fda74e922884fdec1c265efa7f9
Spigot dump: https://gist.github.com/anonymous/14a4a2352b03e35888d07c1a845a4d41

**Comment by beautifulpoison** [comment]
The thing is we have been running it on both for a very long time years... and it never had this issue.

**Comment by MylesIsCool** [comment]
ViaVersion isn't designed to be run on both and just makes it harder when a new version comes out and you update.

The easiest way that will cause you the least hassle is just to remove it from your Bungee and update your Bungee (you're running a 1.11 Bungee, there is no proper 1.12 support).
