### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ColorbombArtz** [Matsv/ViaBackwards#37]
### What is the output url of /viaversion dump?
> Unknown

### How/when does this error happen? login?:
> It does not work. 

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No. It won't let me join and says please use 1.12.2.

**Comment by MylesIsCool** [comment]
We can't help you if you provide no info, ensure you follow the installation guide for ViaVersion then install ViaBackwards.
