### ISSUE TITLE
ViaBackwards not working properly with TrainCarts

### ISSUE THREAD

**Issue by DynamicThijs** [Matsv/ViaBackwards#40]
### What is the output url of /viaversion dump?
https://gist.github.com/2b3e05dcd3e4232685a127fba7a41e93

### How/when does this error happen? login?:
When riding a minecart

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
https://pastebin.com/UcwtCRw4

**Comment by Matsv** [comment]
It looks like traincarts is sending metadata before the entity is spawned, or when the entity is already gone. This warning will be gone next version. You can disable it by changing ‘suppress-metadata-errors’ to ‘true’ in the ViaVersion config
