### ISSUE TITLE
Bug with stairs and slabs.

### ISSUE THREAD

**Issue by TheIntelloBox** [Matsv/ViaBackwards#45]
### What is the output url of /viaversion dump?
The latest version fo ViaVersion and ViaBackwards.

### How/when does this error happen? login?:
My player is in 1.10 and he can't place slabs at the top, and stairs at the top. 

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
No error.

**Comment by creeper123123321** [comment]
#25

**Comment by Neeonn** [comment]
You can use latest DEV build for a temporary fix (version 2.3.2) @TheIntelloBox

**Comment by TheIntelloBox** [comment]
Hello Neeonn ! :D Thanks for your answer and thanks for having fixed this bug ! :D Have a nice morning, or a nice day, or a nice evening, or a nice night ! :D 

TheIntelloBox. :D
