### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by zBoringDrop** [Matsv/ViaBackwards#47]
### What is the output url of /viaversion dump?
> https://pastebin.com/aKcUb1nq

### How/when does this error happen? login?:
> I don't know, i think that it is random (maybe)

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://pastebin.com/9XTN1zCv
No, 0 kick messages

**Comment by Matsv** [comment]
Hi, 

The pastebin is sadly no longer available, could you please reupload your issue? (:

Thanks!
