### ISSUE TITLE
Possible to specify version?

### ISSUE THREAD

**Issue by ysy960108** [Matsv/ViaBackwards#56]
For example, the server is running 1.12.2, because 1.12.2 does not compatible with 1.12/1.12.1, I want clients with 1.12-1.12.2 can connect the server, and clients using 1.11.2 or lower can not.
Thank you.

**Comment by rowan-smith** [comment]
Inside the ViaVersion config I believe you are able to block which protocols are allowed to join the server.

**Comment by MylesIsCool** [comment]
See what rowan-smith said above :)
