### ISSUE TITLE
Invalid keepalive 1.12.1 try to join 1.12.2

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [Matsv/ViaBackwards#60]
### What is the output url of /dump?
https://dump.viaversion.com/d465cba696dc0fb253a2c7dc4594379b4278e79b17e1b071dde41215523d0f19

### How/when does this error happen? login?:
> I have server on 1.12.2 with viabackwards 2.3.1 and viaversion 1.4.1 and when i join thru 1.12.1 it says
[Server] WARN Krynio sent an invalid keepalive! pending keepalive: false got id: 0 expected id: 0

**Comment by Disorbs** [comment]
Try using the Dev build for ViaBackwards had the same issue and it fixed it for me

**Comment by TNTUP** [comment]
the Dev one last time it was built a month ago and the current ViaBackwards got built in July 22 ._.

**Comment by Kryniowesegryderiusz** [comment]
But it works, so it has to be problem with last "stable" version :P

**Comment by TNTUP** [comment]
Maybe, I'll will try it then^^ xD

**Comment by MylesIsCool** [comment]
As seen above dev build fixes afaik
