### ISSUE TITLE
Metadata for entity id: x not sent 

### ISSUE THREAD

**Issue by FaZeMLG** [Matsv/ViaBackwards#61]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/4b7e61c3fee9f861c7015ff8683bfbebcfd9af15bc7c0e2d1bfa749f26dbcf7e

### How/when does this error happen? login?:
> randomly

### Is there an error in the console? Use pastebin.com. Is there a kick message?:

> > [14:17:47] [Netty Epoll Server IO #1/WARN]: [ViaBackwards] Metadata for entity id: 4396 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=0, metaType=Byte, value=0), Metadata(id=1, metaType=VarInt, value=300), Metadata(id=2, metaType=String, value=), Metadata(id=3, metaType=Boolean, value=false), Metadata(id=4, metaType=Boolean, value=false), Metadata(id=5, metaType=Boolean, value=false), Metadata(id=6, metaType=Slot, value=Item(id=81, amount=1, data=0, tag=null))])

**Comment by MylesIsCool** [comment]
This happens due to one of your plugins sending entity data incorrectly, you can suppress these in the ViaVersion config under the suppress-metadata-errors option.
