### ISSUE TITLE
lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by leoncp9** [Matsv/ViaBackwards#62]
### What is the output url of /viaversion dump?  1.4.1
> 

### How/when does this error happen? login?: when i use plugin bedwarts1058 and i buy iron golem, minecaft crash
> 

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
https://drive.google.com/open?id=1KMo_V7liA9TNkUSNowmWq1J43xL4wVYo
>

**Comment by Matsv** [comment]
Please provide more information.

* The ViaVersion dump
* Change 'debug' to 'true' in server.properties and reproduce the issue. You should get more information in your logs

Thanks in advance
