### ISSUE TITLE
Kick on entry

### ISSUE THREAD

**Issue by slxshxr** [Matsv/ViaBackwards#63]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/890b010640e2e3814e95c2b883cc308bd5b32a951f5b95d9f63933bc0ca97f99

### How/when does this error happen? login?:
> On second+ log in, on first try after launch Minecraft it works perfectly, but then it bugs.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> https://pastebin.com/P9s9c2fA

**Comment by Matsv** [comment]
Does this issue still occur for you?

**Comment by Matsv** [comment]
Please ask for a reopen if it still occurs (:
