### ISSUE TITLE
Player disconnect on entry

### ISSUE THREAD

**Issue by alexlazarev98** [Matsv/ViaBackwards#67]
### What is the output URL of /viaversion dump?
> https://dump.viaversion.com/a6ab4b312053a833b89156f4ca9841b716458dc0d28efd2afb3b7472cddf962f

### How/when does this error happen? login?:
>  When player login

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> Just "Disconnected".
### Kick message
> ![screenshot_20180912181939](https://user-images.githubusercontent.com/37180406/45435083-76501e80-b6b8-11e8-89a2-f9bab0b330b1.png)

**Comment by DeadMaster121** [comment]
Having the same issue here

Running Waterfall (fork of bungeecord) when a player joins a server that is running spigot 1.12.2 the player gets disconnected with this error. Using ViaVersion, ViaRewind & ViaBackwards

**Comment by creeper123123321** [comment]
Could anyone who can reproduce this issue get a client's stacktrace with debug enabled? https://wiki.vg/Debugging

**Comment by neox91120** [comment]
Got the same problem
But players can't connect with 1.9 versions !

Anyone have any idea?

**Comment by DeadMaster121** [comment]
The bug has been fixed for me from changing from Spigot 1.12.2 to PaperSpigot 1.12.2

**Comment by DeadMaster121** [comment]
I have found the solution,

For those still wondering you have to update 'TitleManager' to the latest version, I was using an outdated version "2.0.6" I have updated to "2.1.3 (latest)" and everything seems to work for me

(I assume this issue is created if you have enabled the show title on join option)

**Comment by Matsv** [comment]
See above (:
