### ISSUE TITLE
Issue with 1.13 Dev Build

### ISSUE THREAD

**Issue by livmonkey** [Matsv/ViaBackwards#69]
I'm having an issue using via backwards 2.4.0 1.13 dev build. In console it loads, and enabled yet cannot join with an outdated client as the plugin intends.

### What is the output url of /viaversion dump?
> https://dump.viaversion.com/19c7d3538612969579296d4059c817f09987d3ae6c2fa13dc569e90c227ec01a

### How/when does this error happen? login?:
>  N/A

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No console error nor a kick message

**Comment by MylesIsCool** [comment]
The dev build isn't complete hence why it's a dev build. I'd suggest ProtocolSupport for the mean time.
