### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by iamharak** [Matsv/ViaBackwards#71]
When is 1.13 support expected?
Unfortunately, it prevents switching to server version 1.13, and the development is not working yet.

**Comment by MylesIsCool** [comment]
Use ProtocolSupport as an alternative for the time being.

**Comment by iamharak** [comment]
Thanks, but I still use this one but it uses a lot of memory. So I asked when a complete update of ViaBackwards is expected?

**Comment by MylesIsCool** [comment]
There is no expected date.
