### ISSUE TITLE
Book Issue with recent paper change for 1.8.9 clients

### ISSUE THREAD

**Issue by PhanaticD** [Matsv/ViaBackwards#72]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/fa396c3b8c621cd00ab591b664cbec8c17b0f94aa45d642de53c2e4bcb6dde35

### How/when does this error happen? login?:
> Typing out 2 full pages and starting a few characters on page 3 logs you out after you hit done
> started happening after this paper change for 1.12.2 https://github.com/PaperMC/Paper/commit/cedf38aac061173a5f055f7c2acf089627c440c1

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> tried to send too large of a book. Book Size: 716 - Allowed:  514 - Pages: 3
> lost connection: Book too large!

**Comment by Matsv** [comment]
ViaBackwards does not support 1.8.9. Open a bug at the ViaRewind repository instead (:

**Comment by PhanaticD** [comment]
oh oops forgot to close this it was a paper issue
