### ISSUE TITLE
Login error with 1.8 client to 1.12 server ViaRewind

### ISSUE THREAD

**Issue by ber2minsin** [Matsv/ViaBackwards#80]
### What is the output url of /viaversion dump?
> 
https://dump.viaversion.com/dbcac3ac2ac352357afbae5344f9590f8b042dbf1a087a6a5fc7e1ee6ae0e7b6
### How/when does this error happen? login?:
> 
login
### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> 
Kick Message:internal exception java.io.ioexception an existing connection was forcibly closed by the remote host

**Comment by Matsv** [comment]
Not related to ViaBackwards
