### ISSUE TITLE
[Feature Request] 1.10 on 1.11/1.12 server support

### ISSUE THREAD

**Issue by Lmmb74** [Matsv/ViaBackwards#9]
I would like to know if, once Spigot 1.11 gets released, you could add the same feature that ViaBackwards adds 1.10 servers but on 1.11, being both features in the plugin depending on the server it gets installed.

**Comment by Matsv** [comment]
I'll start working on it when Spigot 1.11 is released. I'm currently very limited on time, so I'm not sure about any ETA yet.

**Comment by Lmmb74** [comment]
No trouble. Btw, thanks for taking this feature in consideration :DDD

**Comment by Matsv** [comment]
TODO LIST:

- [ ] Rewrite entity metadata
- [ ] Rewrite entity types
- [ ] Rewrite sounds
- [ ] Rewrite items in the hands of entities

_Storing this todo list here for now_

**Comment by Matsv** [comment]
Do you have any suggestions for replacement entities for the new ones?

**Comment by InfinityAspire** [comment]
Make Llamas Donkeys, Vex to bats, Vindicators and Evokers to Zombie Villagers

**Comment by Lmmb74** [comment]
That sounds nice, and remember to replace also the nitwit profession villagers with another random one.

**Comment by Matsv** [comment]
Bats could work but are probably hard to hit though

**Comment by InfinityAspire** [comment]
So are Vex :b

**Comment by InfinityAspire** [comment]
Btw is there a place for dev builds of ViaBackwards?

**Comment by Matsv** [comment]
Oh yeah maybe, never really play minecraft so didn't try it. (:

I currently work in the 'dev' branch, don't have the viaversion buildserver setup properly at the moment for ViaBackwards devbuilds though.
(https://github.com/Matsv/ViaBackwards/tree/dev)
Please note that if you compile it yourself now, it probably won't work correctly. Didn't rewrite any metadata nor entity types yet. So minecraft will probably crash.

**Comment by InfinityAspire** [comment]
Ah, yeah I was referring to a continuous integration server to just download built jars

**Comment by Matsv** [comment]
There is a job on the ViaVersion buildserver (http://ci.viaversion.com/view/ViaBackwards/). That's the master branch, however.

**Comment by TheIntelloBox** [comment]
Up.

**Comment by Lmmb74** [comment]
Been a long time since last commit u.u

**Comment by TheIntelloBox** [comment]
Yeah.

**Comment by Matsv** [comment]
Yeah, it's been a while. I'm very limited on time sadly, I'm hoping that I have more time next week with Christmas.

**Comment by rj0495** [comment]
What is happening with this?

**Comment by Lmmb74** [comment]
*bump

**Comment by Matsv** [comment]
First of all, I'm sorry for the big delay.

I've made a lot of progress on the 1.11 update.
The only thing (as far as I know) to do are the sound changes.
If you would like to test it, there is a devbuild on the ViaVersion buildserver now: [LINK](https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/)
Please report any bugs / or things to improve (Like better replacement entity, or something) you find. (:

**Does this mean I'll update it to 1.12?**
I'm very limited on time, so I don't know if I'll be able to do it soon. I'll ofcourse work on it when I have the time, but want to finish and perfectionate 1.11 first (:

**Comment by Lmmb74** [comment]
Thanks a lot @Matsv :D

**Comment by Matsv** [comment]
In 1.10 sounds should work correctly now. If you have replacement sound suggestions for non-existing things in 1.10, let me know. (: https://github.com/Matsv/ViaBackwards/blob/dev/core/src/main/java/nl/matsv/viabackwards/protocol/protocol1_10to1_11/packets/SoundPackets.java#L72-L110

**Comment by Matsv** [comment]
Are there any suggestions for the [Parrot](http://minecraft.gamepedia.com/Parrot) replacement entity? (:

**Comment by TheIntelloBox** [comment]
Bat ?

**Comment by rj0495** [comment]
I'd say a Bat too

**Comment by Matsv** [comment]
Alright! And the [Illusioner](http://minecraft.gamepedia.com/Illusioner)?

**Comment by TheIntelloBox** [comment]
Evoker. ;)

**Comment by Matsv** [comment]
Yeah, I have that one at the moment. It sadly doesn't show the bow with that entity.

**Comment by InfinityAspire** [comment]
Skeleton perhaps? Also I'm not sure if it's ViaBackwards but basically every players 1.12 client crashes out of the server when an entity is in render distance with a simple 'lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer'
This is literally all I have loaded [](http://prntscr.com/fi15h3)
Using Spigot and Bungee 1.12, latest ViaVer and Backwards

**Comment by Matsv** [comment]
@InfinityAspire what is the server version? ViaBackwards doesn't handle 1.12 client to 1.11.2 server. so it might be an ViaVersion issue

**Comment by BestMark** [comment]
Thank you for the continuation of the work on the plugin. It's much better than ProtocolSupport.
Is it worth using the latest dev version of the plugin on the public server? Or it is working unstable now?

**Comment by Matsv** [comment]
I wouldn't recommend it at the moment to use it at a production server. 1.10->1.11 is stable, didn't handle replacement sounds yet tho. 1.12 is still pretty new and could be unstable.

**Comment by BestMark** [comment]
Ok, I will be waiting for the stable version of your remarkable plugin.

**Comment by Matsv** [comment]
Updated released now, thanks for testing :)
