### ISSUE TITLE
Recipe book problem 1.12.2 on 1.13.2

### ISSUE THREAD

**Issue by TheMonDon** [Matsv/ViaBackwards#98]
### What is the output URL of /viaversion dump?
> https://dump.viaversion.com/42c8377f8762fe6f811ed4e9699683244d106f6eadecdcadcd6355214bc88c5c

### How/when does this error happen? login?:
> The error happens when trying to open the recipe book in 1.12.2 on a 1.13.2 server. If the recipe book is already open when you try to join, you will get kicked as soon as you try to open a crafting table.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No errors in console. Kick message: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occurred

**Comment by Matsv** [comment]
The client will no longer crash now. However, the recipe book is something I'll implement after the MVP.
