### ISSUE TITLE
1.12.2 login on 1.13.2 spams console

### ISSUE THREAD

**Issue by TheMonDon** [Matsv/ViaBackwards#99]
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/42c8377f8762fe6f811ed4e9699683244d106f6eadecdcadcd6355214bc88c5c

### How/when does this error happen? login?:
> Happens on login with 1.12.2 on 1.13.2 server. Doesn't seem to happen when logging in with 1.13.2 on the 1.13.2 server.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> Yes: https://pastebin.com/9g5Hk8re Doesn't seem to cause any harm, just spams console on login.

**Comment by MylesIsCool** [comment]
1.13.2 isn't complete mapping wise.
